import { useRouter } from "next/router";
import React from "react";
import Dashboard from "@/components/app/dashboard.tsx/Dashboard";
import PrintForm from "@/components/app/printform/PrintForm";
import PrintList from "@/components/app/printlist/PrintList";
import InvoiceForm from "@/components/app/invoiceform/InvoiceForm";
import InvoiceList from "@/components/app/invoicelist/InvoiceList";
import Balance from "@/components/app/balance/Balance";
import Settlement from "@/components/app/settlement/Settlement";
import ClientForm from "@/components/app/clientform/ClientForm";
import ClientList from "@/components/app/clientlist/ClientList";
import Settings from "@/components/app/setting/Settings";
import AboutUs from "@/components/app/aboutus/AboutUs";